#+title: Additional Hooks for Emacs

* About

This package provides additional hooks for Emacs.

Please open [[https://github.com/takaxp/ah/issues][issues]] if you have any idea to extend this package. I will implement new additional hooks as much as possible.

* Configure

Put this package into your ~load-path~. After that, enable =ah-mode= minor mode.

For instance,

#+begin_src emacs-lisp
(when (require 'ah nil t)
  (ah-mode 1))
#+end_src

* Hooks for moving cursor

Providing two hooks for your actions on moving the cursor. It is useful when you want to kick some commands without using =pre-command-hook= and/or =post-command-hook=.

 - ah-before-move-cursor-hook
 - ah-after-move-cursor-hook

** ah-before-move-cursor-hook, ah-after-move-cursor-hook

 - Hook for =next-line=, =previous-line=, =forward-char=, =backward-char=, =syntax-subword-forward=, =syntax-subword-backward=, =move-beginning-of-line=, =move-end-of-line=, =beginning-of-buffer=, and =end-of-buffer=.

* Hooks for =C-g= action

Providing two hooks for your actions on typing =C-g=.

 - ah-before-c-g-hook
 - ah-after-c-g-hook

** ah-before-c-g-hook, ah-after-c-g-hook

 - Hook for =keyboard-quit= and =isearch-abort=.
